package tablas;
// Generated 27-oct-2012 14:04:15 by Hibernate Tools 3.2.1.GA



/**
 * AutoresXPaper generated by hbm2java
 */
public class AutoresXPaper  implements java.io.Serializable {


     private AutoresXPaperId id;

    public AutoresXPaper() {
    }

    public AutoresXPaper(AutoresXPaperId id) {
       this.id = id;
    }
   
    public AutoresXPaperId getId() {
        return this.id;
    }
    
    public void setId(AutoresXPaperId id) {
        this.id = id;
    }




}


