package tablas;
// Generated 07-nov-2012 21:24:32 by Hibernate Tools 3.2.1.GA



/**
 * Autores generated by hbm2java
 */
public class Autores  implements java.io.Serializable {


     private int idAutor;
     private String autor;

    public Autores() {
    }

	
    public Autores(int idAutor) {
        this.idAutor = idAutor;
    }
    public Autores(int idAutor, String autor) {
       this.idAutor = idAutor;
       this.autor = autor;
    }
   
    public int getIdAutor() {
        return this.idAutor;
    }
    
    public void setIdAutor(int idAutor) {
        this.idAutor = idAutor;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }




}


