package tablas;
// Generated 10-12-2012 11:38:58 AM by Hibernate Tools 3.2.1.GA



/**
 * AutoresXPaperId generated by hbm2java
 */
public class AutoresXPaperId  implements java.io.Serializable {


     private int idPaper;
     private int idAutor;

    public AutoresXPaperId() {
    }

    public AutoresXPaperId(int idPaper, int idAutor) {
       this.idPaper = idPaper;
       this.idAutor = idAutor;
    }
   
    public int getIdPaper() {
        return this.idPaper;
    }
    
    public void setIdPaper(int idPaper) {
        this.idPaper = idPaper;
    }
    public int getIdAutor() {
        return this.idAutor;
    }
    
    public void setIdAutor(int idAutor) {
        this.idAutor = idAutor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AutoresXPaperId) ) return false;
		 AutoresXPaperId castOther = ( AutoresXPaperId ) other; 
         
		 return (this.getIdPaper()==castOther.getIdPaper())
 && (this.getIdAutor()==castOther.getIdAutor());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPaper();
         result = 37 * result + this.getIdAutor();
         return result;
   }   


}


