package tablas;
// Generated 10-10-2012 02:24:45 PM by Hibernate Tools 3.2.1.GA



/**
 * AutoresXPaper generated by hbm2java
 */
public class AutoresXPaper  implements java.io.Serializable {


     private int idPaper;
     private Integer idAutor;

    public AutoresXPaper() {
    }

	
    public AutoresXPaper(int idPaper) {
        this.idPaper = idPaper;
    }
    public AutoresXPaper(int idPaper, Integer idAutor) {
       this.idPaper = idPaper;
       this.idAutor = idAutor;
    }
   
    public int getIdPaper() {
        return this.idPaper;
    }
    
    public void setIdPaper(int idPaper) {
        this.idPaper = idPaper;
    }
    public Integer getIdAutor() {
        return this.idAutor;
    }
    
    public void setIdAutor(Integer idAutor) {
        this.idAutor = idAutor;
    }




}


