package tablas;
// Generated 27-oct-2012 14:04:15 by Hibernate Tools 3.2.1.GA



/**
 * FormatoReferencias generated by hbm2java
 */
public class FormatoReferencias  implements java.io.Serializable {


     private int idReferencias;
     private String muestra;
     private boolean enumerables;
     private String norma;
     private int columnasSeccion;

    public FormatoReferencias() {
    }

    public FormatoReferencias(int idReferencias, String muestra, boolean enumerables, String norma, int columnasSeccion) {
       this.idReferencias = idReferencias;
       this.muestra = muestra;
       this.enumerables = enumerables;
       this.norma = norma;
       this.columnasSeccion = columnasSeccion;
    }
   
    public int getIdReferencias() {
        return this.idReferencias;
    }
    
    public void setIdReferencias(int idReferencias) {
        this.idReferencias = idReferencias;
    }
    public String getMuestra() {
        return this.muestra;
    }
    
    public void setMuestra(String muestra) {
        this.muestra = muestra;
    }
    public boolean isEnumerables() {
        return this.enumerables;
    }
    
    public void setEnumerables(boolean enumerables) {
        this.enumerables = enumerables;
    }
    public String getNorma() {
        return this.norma;
    }
    
    public void setNorma(String norma) {
        this.norma = norma;
    }
    public int getColumnasSeccion() {
        return this.columnasSeccion;
    }
    
    public void setColumnasSeccion(int columnasSeccion) {
        this.columnasSeccion = columnasSeccion;
    }




}


