package tablas;
// Generated 07-nov-2012 21:24:32 by Hibernate Tools 3.2.1.GA



/**
 * FormatoPaperId generated by hbm2java
 */
public class FormatoPaperId  implements java.io.Serializable {


     private int idPaper;
     private int idTitulo;
     private int idResumen;
     private int idPalabrasClave;
     private int idIntroduccion;
     private int idRevisionLiteraria;
     private int idMetodologia;
     private int idResultados;
     private int idAgradecimiento;
     private int idReferencias;
     private int idConclusiones;
     private int idAnexo;
     private int idTabla;

    public FormatoPaperId() {
    }

    public FormatoPaperId(int idPaper, int idTitulo, int idResumen, int idPalabrasClave, int idIntroduccion, int idRevisionLiteraria, int idMetodologia, int idResultados, int idAgradecimiento, int idReferencias, int idConclusiones, int idAnexo, int idTabla) {
       this.idPaper = idPaper;
       this.idTitulo = idTitulo;
       this.idResumen = idResumen;
       this.idPalabrasClave = idPalabrasClave;
       this.idIntroduccion = idIntroduccion;
       this.idRevisionLiteraria = idRevisionLiteraria;
       this.idMetodologia = idMetodologia;
       this.idResultados = idResultados;
       this.idAgradecimiento = idAgradecimiento;
       this.idReferencias = idReferencias;
       this.idConclusiones = idConclusiones;
       this.idAnexo = idAnexo;
       this.idTabla = idTabla;
    }
   
    public int getIdPaper() {
        return this.idPaper;
    }
    
    public void setIdPaper(int idPaper) {
        this.idPaper = idPaper;
    }
    public int getIdTitulo() {
        return this.idTitulo;
    }
    
    public void setIdTitulo(int idTitulo) {
        this.idTitulo = idTitulo;
    }
    public int getIdResumen() {
        return this.idResumen;
    }
    
    public void setIdResumen(int idResumen) {
        this.idResumen = idResumen;
    }
    public int getIdPalabrasClave() {
        return this.idPalabrasClave;
    }
    
    public void setIdPalabrasClave(int idPalabrasClave) {
        this.idPalabrasClave = idPalabrasClave;
    }
    public int getIdIntroduccion() {
        return this.idIntroduccion;
    }
    
    public void setIdIntroduccion(int idIntroduccion) {
        this.idIntroduccion = idIntroduccion;
    }
    public int getIdRevisionLiteraria() {
        return this.idRevisionLiteraria;
    }
    
    public void setIdRevisionLiteraria(int idRevisionLiteraria) {
        this.idRevisionLiteraria = idRevisionLiteraria;
    }
    public int getIdMetodologia() {
        return this.idMetodologia;
    }
    
    public void setIdMetodologia(int idMetodologia) {
        this.idMetodologia = idMetodologia;
    }
    public int getIdResultados() {
        return this.idResultados;
    }
    
    public void setIdResultados(int idResultados) {
        this.idResultados = idResultados;
    }
    public int getIdAgradecimiento() {
        return this.idAgradecimiento;
    }
    
    public void setIdAgradecimiento(int idAgradecimiento) {
        this.idAgradecimiento = idAgradecimiento;
    }
    public int getIdReferencias() {
        return this.idReferencias;
    }
    
    public void setIdReferencias(int idReferencias) {
        this.idReferencias = idReferencias;
    }
    public int getIdConclusiones() {
        return this.idConclusiones;
    }
    
    public void setIdConclusiones(int idConclusiones) {
        this.idConclusiones = idConclusiones;
    }
    public int getIdAnexo() {
        return this.idAnexo;
    }
    
    public void setIdAnexo(int idAnexo) {
        this.idAnexo = idAnexo;
    }
    public int getIdTabla() {
        return this.idTabla;
    }
    
    public void setIdTabla(int idTabla) {
        this.idTabla = idTabla;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FormatoPaperId) ) return false;
		 FormatoPaperId castOther = ( FormatoPaperId ) other; 
         
		 return (this.getIdPaper()==castOther.getIdPaper())
 && (this.getIdTitulo()==castOther.getIdTitulo())
 && (this.getIdResumen()==castOther.getIdResumen())
 && (this.getIdPalabrasClave()==castOther.getIdPalabrasClave())
 && (this.getIdIntroduccion()==castOther.getIdIntroduccion())
 && (this.getIdRevisionLiteraria()==castOther.getIdRevisionLiteraria())
 && (this.getIdMetodologia()==castOther.getIdMetodologia())
 && (this.getIdResultados()==castOther.getIdResultados())
 && (this.getIdAgradecimiento()==castOther.getIdAgradecimiento())
 && (this.getIdReferencias()==castOther.getIdReferencias())
 && (this.getIdConclusiones()==castOther.getIdConclusiones())
 && (this.getIdAnexo()==castOther.getIdAnexo())
 && (this.getIdTabla()==castOther.getIdTabla());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPaper();
         result = 37 * result + this.getIdTitulo();
         result = 37 * result + this.getIdResumen();
         result = 37 * result + this.getIdPalabrasClave();
         result = 37 * result + this.getIdIntroduccion();
         result = 37 * result + this.getIdRevisionLiteraria();
         result = 37 * result + this.getIdMetodologia();
         result = 37 * result + this.getIdResultados();
         result = 37 * result + this.getIdAgradecimiento();
         result = 37 * result + this.getIdReferencias();
         result = 37 * result + this.getIdConclusiones();
         result = 37 * result + this.getIdAnexo();
         result = 37 * result + this.getIdTabla();
         return result;
   }   


}


