package tablas;
// Generated 09-13-2012 06:37:09 PM by Hibernate Tools 3.2.1.GA



/**
 * FormatoMetodologia generated by hbm2java
 */
public class FormatoMetodologia  implements java.io.Serializable {


     private int idMetodologia;
     private String muestra;
     private int minimoPalabras;
     private int maximoPalabras;
     private int columnasSeccion;

    public FormatoMetodologia() {
    }

    public FormatoMetodologia(int idMetodologia, String muestra, int minimoPalabras, int maximoPalabras, int columnasSeccion) {
       this.idMetodologia = idMetodologia;
       this.muestra = muestra;
       this.minimoPalabras = minimoPalabras;
       this.maximoPalabras = maximoPalabras;
       this.columnasSeccion = columnasSeccion;
    }
   
    public int getIdMetodologia() {
        return this.idMetodologia;
    }
    
    public void setIdMetodologia(int idMetodologia) {
        this.idMetodologia = idMetodologia;
    }
    public String getMuestra() {
        return this.muestra;
    }
    
    public void setMuestra(String muestra) {
        this.muestra = muestra;
    }
    public int getMinimoPalabras() {
        return this.minimoPalabras;
    }
    
    public void setMinimoPalabras(int minimoPalabras) {
        this.minimoPalabras = minimoPalabras;
    }
    public int getMaximoPalabras() {
        return this.maximoPalabras;
    }
    
    public void setMaximoPalabras(int maximoPalabras) {
        this.maximoPalabras = maximoPalabras;
    }
    public int getColumnasSeccion() {
        return this.columnasSeccion;
    }
    
    public void setColumnasSeccion(int columnasSeccion) {
        this.columnasSeccion = columnasSeccion;
    }




}


