package tablas;
// Generated 27-oct-2012 14:04:15 by Hibernate Tools 3.2.1.GA



/**
 * FormatoConclusiones generated by hbm2java
 */
public class FormatoConclusiones  implements java.io.Serializable {


     private int idConclusiones;
     private String muestra;
     private boolean enumerables;
     private int minimoPalabrasEnumerable;
     private int maximoPalabrasEnumerable;
     private int minimoPalabrasBloque;
     private int maximoPalabrasBloque;
     private int columnasSeccion;

    public FormatoConclusiones() {
    }

    public FormatoConclusiones(int idConclusiones, String muestra, boolean enumerables, int minimoPalabrasEnumerable, int maximoPalabrasEnumerable, int minimoPalabrasBloque, int maximoPalabrasBloque, int columnasSeccion) {
       this.idConclusiones = idConclusiones;
       this.muestra = muestra;
       this.enumerables = enumerables;
       this.minimoPalabrasEnumerable = minimoPalabrasEnumerable;
       this.maximoPalabrasEnumerable = maximoPalabrasEnumerable;
       this.minimoPalabrasBloque = minimoPalabrasBloque;
       this.maximoPalabrasBloque = maximoPalabrasBloque;
       this.columnasSeccion = columnasSeccion;
    }
   
    public int getIdConclusiones() {
        return this.idConclusiones;
    }
    
    public void setIdConclusiones(int idConclusiones) {
        this.idConclusiones = idConclusiones;
    }
    public String getMuestra() {
        return this.muestra;
    }
    
    public void setMuestra(String muestra) {
        this.muestra = muestra;
    }
    public boolean isEnumerables() {
        return this.enumerables;
    }
    
    public void setEnumerables(boolean enumerables) {
        this.enumerables = enumerables;
    }
    public int getMinimoPalabrasEnumerable() {
        return this.minimoPalabrasEnumerable;
    }
    
    public void setMinimoPalabrasEnumerable(int minimoPalabrasEnumerable) {
        this.minimoPalabrasEnumerable = minimoPalabrasEnumerable;
    }
    public int getMaximoPalabrasEnumerable() {
        return this.maximoPalabrasEnumerable;
    }
    
    public void setMaximoPalabrasEnumerable(int maximoPalabrasEnumerable) {
        this.maximoPalabrasEnumerable = maximoPalabrasEnumerable;
    }
    public int getMinimoPalabrasBloque() {
        return this.minimoPalabrasBloque;
    }
    
    public void setMinimoPalabrasBloque(int minimoPalabrasBloque) {
        this.minimoPalabrasBloque = minimoPalabrasBloque;
    }
    public int getMaximoPalabrasBloque() {
        return this.maximoPalabrasBloque;
    }
    
    public void setMaximoPalabrasBloque(int maximoPalabrasBloque) {
        this.maximoPalabrasBloque = maximoPalabrasBloque;
    }
    public int getColumnasSeccion() {
        return this.columnasSeccion;
    }
    
    public void setColumnasSeccion(int columnasSeccion) {
        this.columnasSeccion = columnasSeccion;
    }




}


