package tablas;
// Generated 10-12-2012 11:38:58 AM by Hibernate Tools 3.2.1.GA



/**
 * FormatoPaper generated by hbm2java
 */
public class FormatoPaper  implements java.io.Serializable {


     private FormatoPaperId id;
     private String nombre;

    public FormatoPaper() {
    }

	
    public FormatoPaper(FormatoPaperId id) {
        this.id = id;
    }
    public FormatoPaper(FormatoPaperId id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   
    public FormatoPaperId getId() {
        return this.id;
    }
    
    public void setId(FormatoPaperId id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


