package tablas;
// Generated 07-nov-2012 21:24:32 by Hibernate Tools 3.2.1.GA



/**
 * FormatoAnexo generated by hbm2java
 */
public class FormatoAnexo  implements java.io.Serializable {


     private int idAnexo;
     private String muestra;
     private int columnasSeccion;
     private int minimoPalabras;
     private int maximoPalabras;
     private int minimoTotal;
     private int maximoTotal;

    public FormatoAnexo() {
    }

    public FormatoAnexo(int idAnexo, String muestra, int columnasSeccion, int minimoPalabras, int maximoPalabras, int minimoTotal, int maximoTotal) {
       this.idAnexo = idAnexo;
       this.muestra = muestra;
       this.columnasSeccion = columnasSeccion;
       this.minimoPalabras = minimoPalabras;
       this.maximoPalabras = maximoPalabras;
       this.minimoTotal = minimoTotal;
       this.maximoTotal = maximoTotal;
    }
   
    public int getIdAnexo() {
        return this.idAnexo;
    }
    
    public void setIdAnexo(int idAnexo) {
        this.idAnexo = idAnexo;
    }
    public String getMuestra() {
        return this.muestra;
    }
    
    public void setMuestra(String muestra) {
        this.muestra = muestra;
    }
    public int getColumnasSeccion() {
        return this.columnasSeccion;
    }
    
    public void setColumnasSeccion(int columnasSeccion) {
        this.columnasSeccion = columnasSeccion;
    }
    public int getMinimoPalabras() {
        return this.minimoPalabras;
    }
    
    public void setMinimoPalabras(int minimoPalabras) {
        this.minimoPalabras = minimoPalabras;
    }
    public int getMaximoPalabras() {
        return this.maximoPalabras;
    }
    
    public void setMaximoPalabras(int maximoPalabras) {
        this.maximoPalabras = maximoPalabras;
    }
    public int getMinimoTotal() {
        return this.minimoTotal;
    }
    
    public void setMinimoTotal(int minimoTotal) {
        this.minimoTotal = minimoTotal;
    }
    public int getMaximoTotal() {
        return this.maximoTotal;
    }
    
    public void setMaximoTotal(int maximoTotal) {
        this.maximoTotal = maximoTotal;
    }




}


