package tablas;
// Generated 10-12-2012 11:38:58 AM by Hibernate Tools 3.2.1.GA



/**
 * FormatoTabla generated by hbm2java
 */
public class FormatoTabla  implements java.io.Serializable {


     private int id;
     private int idTabla;
     private int columnasSeccion;
     private int ancho;
     private int alto;

    public FormatoTabla() {
    }

    public FormatoTabla(int id, int idTabla, int columnasSeccion, int ancho, int alto) {
       this.id = id;
       this.idTabla = idTabla;
       this.columnasSeccion = columnasSeccion;
       this.ancho = ancho;
       this.alto = alto;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdTabla() {
        return this.idTabla;
    }
    
    public void setIdTabla(int idTabla) {
        this.idTabla = idTabla;
    }
    public int getColumnasSeccion() {
        return this.columnasSeccion;
    }
    
    public void setColumnasSeccion(int columnasSeccion) {
        this.columnasSeccion = columnasSeccion;
    }
    public int getAncho() {
        return this.ancho;
    }
    
    public void setAncho(int ancho) {
        this.ancho = ancho;
    }
    public int getAlto() {
        return this.alto;
    }
    
    public void setAlto(int alto) {
        this.alto = alto;
    }




}


