package tablas;
// Generated 07-nov-2012 21:24:32 by Hibernate Tools 3.2.1.GA



/**
 * FormatoTitulo generated by hbm2java
 */
public class FormatoTitulo  implements java.io.Serializable {


     private int idTitulo;
     private String muestra;
     private int minimoAutores;
     private int maximoAutores;

    public FormatoTitulo() {
    }

    public FormatoTitulo(int idTitulo, String muestra, int minimoAutores, int maximoAutores) {
       this.idTitulo = idTitulo;
       this.muestra = muestra;
       this.minimoAutores = minimoAutores;
       this.maximoAutores = maximoAutores;
    }
   
    public int getIdTitulo() {
        return this.idTitulo;
    }
    
    public void setIdTitulo(int idTitulo) {
        this.idTitulo = idTitulo;
    }
    public String getMuestra() {
        return this.muestra;
    }
    
    public void setMuestra(String muestra) {
        this.muestra = muestra;
    }
    public int getMinimoAutores() {
        return this.minimoAutores;
    }
    
    public void setMinimoAutores(int minimoAutores) {
        this.minimoAutores = minimoAutores;
    }
    public int getMaximoAutores() {
        return this.maximoAutores;
    }
    
    public void setMaximoAutores(int maximoAutores) {
        this.maximoAutores = maximoAutores;
    }




}


