package tablas;
// Generated 07-nov-2012 21:24:32 by Hibernate Tools 3.2.1.GA



/**
 * FormatoIntroduccion generated by hbm2java
 */
public class FormatoIntroduccion  implements java.io.Serializable {


     private int idIntroduccion;
     private String muestra;
     private int minimoPalabras;
     private int maximoPalabras;
     private int columnasSeccion;

    public FormatoIntroduccion() {
    }

    public FormatoIntroduccion(int idIntroduccion, String muestra, int minimoPalabras, int maximoPalabras, int columnasSeccion) {
       this.idIntroduccion = idIntroduccion;
       this.muestra = muestra;
       this.minimoPalabras = minimoPalabras;
       this.maximoPalabras = maximoPalabras;
       this.columnasSeccion = columnasSeccion;
    }
   
    public int getIdIntroduccion() {
        return this.idIntroduccion;
    }
    
    public void setIdIntroduccion(int idIntroduccion) {
        this.idIntroduccion = idIntroduccion;
    }
    public String getMuestra() {
        return this.muestra;
    }
    
    public void setMuestra(String muestra) {
        this.muestra = muestra;
    }
    public int getMinimoPalabras() {
        return this.minimoPalabras;
    }
    
    public void setMinimoPalabras(int minimoPalabras) {
        this.minimoPalabras = minimoPalabras;
    }
    public int getMaximoPalabras() {
        return this.maximoPalabras;
    }
    
    public void setMaximoPalabras(int maximoPalabras) {
        this.maximoPalabras = maximoPalabras;
    }
    public int getColumnasSeccion() {
        return this.columnasSeccion;
    }
    
    public void setColumnasSeccion(int columnasSeccion) {
        this.columnasSeccion = columnasSeccion;
    }




}


