package tablas;
// Generated 10-12-2012 11:38:58 AM by Hibernate Tools 3.2.1.GA



/**
 * FormatoRevisionLiteratura generated by hbm2java
 */
public class FormatoRevisionLiteratura  implements java.io.Serializable {


     private int idRevisionLiteratura;
     private String muestra;
     private int minimoPalabras;
     private int maximoPalabras;
     private int columnasSeccion;

    public FormatoRevisionLiteratura() {
    }

    public FormatoRevisionLiteratura(int idRevisionLiteratura, String muestra, int minimoPalabras, int maximoPalabras, int columnasSeccion) {
       this.idRevisionLiteratura = idRevisionLiteratura;
       this.muestra = muestra;
       this.minimoPalabras = minimoPalabras;
       this.maximoPalabras = maximoPalabras;
       this.columnasSeccion = columnasSeccion;
    }
   
    public int getIdRevisionLiteratura() {
        return this.idRevisionLiteratura;
    }
    
    public void setIdRevisionLiteratura(int idRevisionLiteratura) {
        this.idRevisionLiteratura = idRevisionLiteratura;
    }
    public String getMuestra() {
        return this.muestra;
    }
    
    public void setMuestra(String muestra) {
        this.muestra = muestra;
    }
    public int getMinimoPalabras() {
        return this.minimoPalabras;
    }
    
    public void setMinimoPalabras(int minimoPalabras) {
        this.minimoPalabras = minimoPalabras;
    }
    public int getMaximoPalabras() {
        return this.maximoPalabras;
    }
    
    public void setMaximoPalabras(int maximoPalabras) {
        this.maximoPalabras = maximoPalabras;
    }
    public int getColumnasSeccion() {
        return this.columnasSeccion;
    }
    
    public void setColumnasSeccion(int columnasSeccion) {
        this.columnasSeccion = columnasSeccion;
    }




}


