package tablas;
// Generated 10-10-2012 02:24:45 PM by Hibernate Tools 3.2.1.GA



/**
 * FrasesClaveXPaper generated by hbm2java
 */
public class FrasesClaveXPaper  implements java.io.Serializable {


     private FrasesClaveXPaperId id;

    public FrasesClaveXPaper() {
    }

    public FrasesClaveXPaper(FrasesClaveXPaperId id) {
       this.id = id;
    }
   
    public FrasesClaveXPaperId getId() {
        return this.id;
    }
    
    public void setId(FrasesClaveXPaperId id) {
        this.id = id;
    }




}


