package tablas;
// Generated 09-13-2012 06:37:09 PM by Hibernate Tools 3.2.1.GA



/**
 * FrasesClaveXPaperId generated by hbm2java
 */
public class FrasesClaveXPaperId  implements java.io.Serializable {


     private int idPaper;
     private String fraseClave;

    public FrasesClaveXPaperId() {
    }

    public FrasesClaveXPaperId(int idPaper, String fraseClave) {
       this.idPaper = idPaper;
       this.fraseClave = fraseClave;
    }
   
    public int getIdPaper() {
        return this.idPaper;
    }
    
    public void setIdPaper(int idPaper) {
        this.idPaper = idPaper;
    }
    public String getFraseClave() {
        return this.fraseClave;
    }
    
    public void setFraseClave(String fraseClave) {
        this.fraseClave = fraseClave;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FrasesClaveXPaperId) ) return false;
		 FrasesClaveXPaperId castOther = ( FrasesClaveXPaperId ) other; 
         
		 return (this.getIdPaper()==castOther.getIdPaper())
 && ( (this.getFraseClave()==castOther.getFraseClave()) || ( this.getFraseClave()!=null && castOther.getFraseClave()!=null && this.getFraseClave().equals(castOther.getFraseClave()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPaper();
         result = 37 * result + ( getFraseClave() == null ? 0 : this.getFraseClave().hashCode() );
         return result;
   }   


}


