package tablas;
// Generated 10-10-2012 02:24:45 PM by Hibernate Tools 3.2.1.GA



/**
 * PermisosXRoles generated by hbm2java
 */
public class PermisosXRoles  implements java.io.Serializable {


     private PermisosXRolesId id;

    public PermisosXRoles() {
    }

    public PermisosXRoles(PermisosXRolesId id) {
       this.id = id;
    }
   
    public PermisosXRolesId getId() {
        return this.id;
    }
    
    public void setId(PermisosXRolesId id) {
        this.id = id;
    }




}


