package tablas;
// Generated 07-nov-2012 21:24:32 by Hibernate Tools 3.2.1.GA



/**
 * PermisosXRoles generated by hbm2java
 */
public class PermisosXRoles  implements java.io.Serializable {


     private PermisosXRolesId id;

    public PermisosXRoles() {
    }

    public PermisosXRoles(PermisosXRolesId id) {
       this.id = id;
    }
   
    public PermisosXRolesId getId() {
        return this.id;
    }
    
    public void setId(PermisosXRolesId id) {
        this.id = id;
    }




}


