package tablas;
// Generated 09-13-2012 06:37:09 PM by Hibernate Tools 3.2.1.GA



/**
 * Permisos generated by hbm2java
 */
public class Permisos  implements java.io.Serializable {


     private int idPermiso;
     private String descripcion;

    public Permisos() {
    }

    public Permisos(int idPermiso, String descripcion) {
       this.idPermiso = idPermiso;
       this.descripcion = descripcion;
    }
   
    public int getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(int idPermiso) {
        this.idPermiso = idPermiso;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


