package tablas;
// Generated 07-nov-2012 21:24:32 by Hibernate Tools 3.2.1.GA



/**
 * Permisos generated by hbm2java
 */
public class Permisos  implements java.io.Serializable {


     private int idPermiso;
     private String descripcion;

    public Permisos() {
    }

    public Permisos(int idPermiso, String descripcion) {
       this.idPermiso = idPermiso;
       this.descripcion = descripcion;
    }
   
    public int getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(int idPermiso) {
        this.idPermiso = idPermiso;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


