package tablas;
// Generated 07-nov-2012 21:24:32 by Hibernate Tools 3.2.1.GA



/**
 * PermisosXRolesId generated by hbm2java
 */
public class PermisosXRolesId  implements java.io.Serializable {


     private int idPermiso;
     private int idRol;

    public PermisosXRolesId() {
    }

    public PermisosXRolesId(int idPermiso, int idRol) {
       this.idPermiso = idPermiso;
       this.idRol = idRol;
    }
   
    public int getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(int idPermiso) {
        this.idPermiso = idPermiso;
    }
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PermisosXRolesId) ) return false;
		 PermisosXRolesId castOther = ( PermisosXRolesId ) other; 
         
		 return (this.getIdPermiso()==castOther.getIdPermiso())
 && (this.getIdRol()==castOther.getIdRol());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPermiso();
         result = 37 * result + this.getIdRol();
         return result;
   }   


}


