package tablas;
// Generated 27-oct-2012 14:04:15 by Hibernate Tools 3.2.1.GA



/**
 * RolesXUsuarios generated by hbm2java
 */
public class RolesXUsuarios  implements java.io.Serializable {


     private RolesXUsuariosId id;

    public RolesXUsuarios() {
    }

    public RolesXUsuarios(RolesXUsuariosId id) {
       this.id = id;
    }
   
    public RolesXUsuariosId getId() {
        return this.id;
    }
    
    public void setId(RolesXUsuariosId id) {
        this.id = id;
    }




}


