package tablas;
// Generated 27-oct-2012 14:04:15 by Hibernate Tools 3.2.1.GA



/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private int idRol;
     private String descripcion;

    public Roles() {
    }

    public Roles(int idRol, String descripcion) {
       this.idRol = idRol;
       this.descripcion = descripcion;
    }
   
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


