package tablas;
// Generated 07-nov-2012 21:24:32 by Hibernate Tools 3.2.1.GA



/**
 * Tablas generated by hbm2java
 */
public class Tablas  implements java.io.Serializable {


     private int idTabla;
     private byte[] tabla;
     private Integer idTipo;

    public Tablas() {
    }

	
    public Tablas(int idTabla) {
        this.idTabla = idTabla;
    }
    public Tablas(int idTabla, byte[] tabla, Integer idTipo) {
       this.idTabla = idTabla;
       this.tabla = tabla;
       this.idTipo = idTipo;
    }
   
    public int getIdTabla() {
        return this.idTabla;
    }
    
    public void setIdTabla(int idTabla) {
        this.idTabla = idTabla;
    }
    public byte[] getTabla() {
        return this.tabla;
    }
    
    public void setTabla(byte[] tabla) {
        this.tabla = tabla;
    }
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }




}


