package tablas;
// Generated 07-nov-2012 21:24:32 by Hibernate Tools 3.2.1.GA



/**
 * TiposTablas generated by hbm2java
 */
public class TiposTablas  implements java.io.Serializable {


     private int idTipo;
     private Boolean AUnaColumna;

    public TiposTablas() {
    }

	
    public TiposTablas(int idTipo) {
        this.idTipo = idTipo;
    }
    public TiposTablas(int idTipo, Boolean AUnaColumna) {
       this.idTipo = idTipo;
       this.AUnaColumna = AUnaColumna;
    }
   
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public Boolean getAUnaColumna() {
        return this.AUnaColumna;
    }
    
    public void setAUnaColumna(Boolean AUnaColumna) {
        this.AUnaColumna = AUnaColumna;
    }




}


