package tablas;
// Generated 10-10-2012 02:24:45 PM by Hibernate Tools 3.2.1.GA



/**
 * UsuariosNoAprobados generated by hbm2java
 */
public class UsuariosNoAprobados  implements java.io.Serializable {


     private String correo;
     private String nombres;
     private String apellidos;
     private String password;
     private boolean aprobado;

    public UsuariosNoAprobados() {
    }

    public UsuariosNoAprobados(String correo, String nombres, String apellidos, String password, boolean aprobado) {
       this.correo = correo;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.password = password;
       this.aprobado = aprobado;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isAprobado() {
        return this.aprobado;
    }
    
    public void setAprobado(boolean aprobado) {
        this.aprobado = aprobado;
    }




}


